#  Copyright 2018 Dr. Michael Menzel, Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--global', 'gulp-cli']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'dist/function.zip', 'gs://${_BUCKET}/function$COMMIT_SHA.zip']
- name: gcr.io/cloud-builders/gcloud
  args: ['functions', 'deploy', 'example-hangouts-chat-bot-cloud-function-nodejs', '--source=gs://${_BUCKET}/function$COMMIT_SHA.zip', '--runtime=nodejs8', '--trigger-http', '--entry-point=handler', '--env-vars-file=production.env.yaml']
substitutions:
  _BUCKET: example-hangouts-chat-bot-cloud-function-nodejs # default value